### PR TITLE
fixes #7 Posting to public chat feature added

### LINKED ISSUE #7: Posting announcements to public chat
To be able to post message regarding advancements of Susi AI, to public chat. This will aware people about the new features added to Susi AI.

### PR DESCRIPTION
**Pull request by Manveer695**
Also improved documentation

### CODE REVIEW

**Comment by mariobehling** [comment]
You are changing 19 and you did not match this PR with an issue. Which issue is this related to? Why are you changing so many different things in a single PR? Also commits should be squashed.

Please read the guidelines for coding programs so we are all aligned. Especially the section about issues and PRs: https://docs.google.com/document/d/1E4kNgrOSw64R2IAG45JSIgQL9Yxia-mG2dqlRcrUo-U/edit#heading=h.wiqr99xc88ji

We need to make it easy for reviewers. Thanks.

**Comment by Manveer695** [comment]
@mariobehling Sorry, if any inconvenience caused. I will resolve the stated issues soon. Thank you for pointing out.

**Comment by mariobehling** [comment]
As this project is at its beginning stage I am merging this. However please do follow the best practices at FOSSASIA from now on. 

It seems a lot of changes are unrelated to the actual issue. It is very important that we all follow the same policy. This will speed up our collaboration and make it easier and faster for reviewers.

It would be great if you really start to follow the best practices. It is of utmost importance to follow the best practices. We all follow the best practices and I hope you also follow best practices now as best practices help us to speed up our process and work together more efficiently. That is why - best practices - are very very important for us.

Please do follow our best practices. Thank you for following best practices. We appreciate working together following best practices. Cheers.

**Comment by mariobehling** [comment]
In case I am not clear. We need everyone to align on a common workflow and follow best practices. We can define more details. A good starting point is here http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

Please help us now and save all of us time. Follow best practices.

Thank you very much.

**Comment by mariobehling** [comment]
To be sure: Follow best practices. \

Please cooperate. Cheers.

**Comment by Manveer695** [comment]
@mariobehling I got your point that it is very very important to follow best practices. I will surely cooperate and will follow best practices. As you said, it will keep us all aligned on a common workflow and increase the efficiency of the team. I have given the blog article a thorough reading, and will definitely follow the best practices of Fossasia from now on. Thank you so much.

**Pull request merged**
