### PR TITLE
Added image type response from viber bot

### PR DESCRIPTION
**Pull request by AliAyub007**
Fixes issue #18 

Changes:

Added image type response from SUSI Viber bot. 

Screenshots for the change: 

19047270_817586001725842_604205733_o

### CODE REVIEW

**Comment by AliAyub007** [comment]
@Manveer695 @saurabhjn76 @betterclever Kindly review this PR.

**Comment by AliAyub007** [comment]
@betterclever Yes I am raising this issue in susi_server and as soon it gets implemented in server then it will like map i.e we will just check for the type of response.

**Comment by dynamitechetan** [comment]
please resolve the conflicts.

**Comment by Manveer695** [comment]
@AliAyub007 as said by Chatan, please resolve the conflicts.

**Pull request closed without merging**
